add missing notify2 dependency
After running ./setup.sh and trying to use jarvis I got the error:
ImportError: No module named notify2.

Adding notify2 in requirements.txt file to solve it.